// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tracewire.Infrastructure;

#nullable disable

namespace Tracewire.Infrastructure.Migrations
{
    [DbContext(typeof(TracewireDbContext))]
    partial class TracewireDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "event_type", new[] { "prompt", "tool_call", "model_response", "memory_write", "error", "retry" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "hitl_status", new[] { "none", "paused", "resumed", "timed_out" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "replay_policy", new[] { "warn", "block", "require_approval" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trace_status", new[] { "running", "success", "error" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tracewire.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("HitlDecision")
                        .HasColumnType("jsonb");

                    b.Property<int>("HitlStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("HitlTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<string>("SideEffects")
                        .HasColumnType("jsonb");

                    b.Property<string>("StateSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<int>("StepOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("StepOrder"));

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TraceId");

                    b.HasIndex("TraceId", "BranchName", "Depth", "StepOrder");

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Event_PayloadSize", "octet_length(\"Payload\"::text) <= 102400");

                            t.HasCheckConstraint("CK_Event_StateSnapshotSize", "octet_length(\"StateSnapshot\"::text) <= 524288");
                        });
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Trace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<byte?>("TraceFlags")
                        .HasColumnType("smallint");

                    b.Property<string>("TraceState")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Traces");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReplayPolicy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Tracewire.Domain.Entities.Workspace", "Workspace")
                        .WithMany("ApiKeys")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Event", b =>
                {
                    b.HasOne("Tracewire.Domain.Entities.Event", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tracewire.Domain.Entities.Trace", "Trace")
                        .WithMany("Events")
                        .HasForeignKey("TraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Trace");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Trace", b =>
                {
                    b.HasOne("Tracewire.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Traces")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("Tracewire.Domain.Entities.Organization", "Organization")
                        .WithMany("Workspaces")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Event", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Trace", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Tracewire.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Traces");
                });
#pragma warning restore 612, 618
        }
    }
}
